services:
  - type: web
    name: parser
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        value: "7809115494:AAHSe9imJdXIcnfPV2aAEDa32lxZyw084Ec"
