services:
  - type: web
    name: parser-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        value: "7809115494:AAHSe91mJdXICnfPV2aAEDa–ó21xZyw084EC"
      - key: CHROME_BIN
        value: "/usr/bin/google-chrome-stable"
      - key: CHROMEDRIVER_PATH
        value: "/usr/local/bin/chromedriver"
    buildEnvVars:
      - key: PIP_NO_CACHE_DIR
        value: "false"
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: "true"
      - key: INSTALL_CHROMIUM
        value: "true"
    installPackages:
      - chromium
      - chromium-driver
