services:
  - type: web
    name: parser-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        value: "7809115494:AAHSe91mJdXICnfPV2aAEDa–ó21xZyw084EC"
      - key: CHROME_BIN
        value: "/usr/bin/google-chrome-stable"
      - key: CHROMEDRIVER_PATH
        value: "/usr/local/bin/chromedriver"

